Models/Produit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TP03.Models
{
    public class Produit
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
    }
}

Controllers/ProduitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TP03.Models;

namespace TP03.Controllers
{
    public class ProduitController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Hello to the home page of TP3";
            return View();
        }

        public ActionResult DisplayOneProduct()
        {
            Produit produit = new Produit
            {
                Id = 1,
                Name = "Test",
                Price = 10
            };
            return View(produit);
        }

        public ActionResult DisplayManyProducts()
        {
            List<Produit> produits = new List<Produit>
            {
                new Produit { Id = 1, Name = "Produit 1", Price = 10 },
                new Produit { Id = 2, Name = "Produit 2", Price = 20 },
                new Produit { Id = 3, Name = "Produit 3", Price = 30 }
            };

            ViewData["produits"] = produits;
            return View();
        }
    }
}

Views/Produit/DisplayManyProducts.cshtml
@{
    ViewBag.Title = "DisplayManyProducts";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<TP03.Models.Produit> produits = ViewData["produits"] as List<TP03.Models.Produit>;
}

<table class="table table-bordered table-hover" style="margin-top:100px">
    <tr>
        <th>Product ID</th>
        <th>Product Name</th>
        <th>Product Price</th>
    </tr>
    @foreach (var produit in produits)
    {
        <tr>
            <td>@produit.Id</td>

            <td>@produit.Name</td>

            <td>@produit.Price</td>
        </tr>
    }
</table>

Views/Produit/DisplayOneProduct.cshtml
@{
    ViewBag.Title = "DisplayOneProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-bordered table-hover" style="margin-top:100px">
    <tr>
        <td>Product ID</td>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <td>Product Name</td>
        <td>@Model.Name</td>
    </tr>
    <tr>
        <td>Product Price</td>
        <td>@Model.Price</td>
    </tr>
</table>

Views/Produit/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.Message</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TP03</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_Menu")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - TP03</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Menu.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
    <div class="container">
        @Html.ActionLink("Home", "Index", "Produit", new { area = "" }, new { @class = "navbar-brand" })
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li>@Html.ActionLink("Home", "Index", "Produit", new { area = "" }, new { @class = "nav-link" })</li>
                <li>@Html.ActionLink("Display One", "DisplayOneProduct", "Produit", new { area = "" }, new { @class = "nav-link" })</li>
                <li>@Html.ActionLink("Display Many", "DisplayManyProducts", "Produit", new { area = "" }, new { @class = "nav-link" })</li>
            </ul>
        </div>
    </div>
</nav>